program: main.py
method: grid
metric:
  name: mean_fold_acc
  goal: maximize
parameters:
  multiclass_strategy:
    values: ['oao', 'native']
  pca_cev: 
    values: [0.7, 0.8, 0.85, 0.9, 0.95]
  xgb_n_estimators:
    values: [100, 200, 300]
  xgb_max_depth: 
    values: [3, 6, 8, 10]
  xgb_tree_method: 
    value: 'hist'
  
command:
  - .\venv\Scripts\python.exe
  - ${program}
  - "-m"
  - "xgboost"
  - "-d"
  - "medeiros"
  - ${args}