program: main.py
method: grid
metric:
  name: mean_fold_acc
  goal: maximize
parameters:
  pca_cev: 
    values: [0.7, 0.8, 0.85, 0.9, 0.95]
  xgb_eval_metric': 
    value: 'merror'
  xgb_objective': 
    value: 'softmax'
  xgb_max_depth': 
    values: [3, 6, 8, 10]
  xgb_tree_method': 
    value: 'hist'
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "-m"
  - "xgboost"
  - "-d"
  - "medeiros"
  - ${args}